# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Sustainability
author: Wim Yedema
# logo: logo.png

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: force

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib

# Information about where the book exists on the web
repository:
  url: https://github.com/WimYedema/sustainability # Online location of your book
  path_to_book: doc # Optional path to your book, relative to the repository root
  branch: master # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true

parse:
  myst_enable_extensions: # default extensions to enable in the myst parser. See https://myst-parser.readthedocs.io/en/latest/using/syntax-optional.html
    - amsmath
    - colon_fence
    - deflist
    - dollarmath
    # - html_admonition
    # - html_image
    - linkify
    # - replacements
    - smartquotes
    - substitution
    - tasklist
    - fieldlist
  myst_url_schemes: [mailto, http, https] # URI schemes that will be recognised as external URLs in Markdown links
  myst_dmath_double_inline: true # Allow display math ($$) within an inline context

sphinx:
  # extra_extensions:
  #   - "autoapi.extension"
  #   - "sphinx.ext.autodoc"
  #   - "sphinx.ext.napoleon"
  #   - "sphinx.ext.viewcode"
  #   - "sphinxcontrib.mermaid"
  config:
    add_module_names: False
    # autosummary_generate: True
    # autodoc_typehints: "description"
    # autoapi_root: "api"
    # autoapi_dirs:
    #   - "../flow"
    #   - "../flow/lang/parse"
    #   - "../flow/lib"
    # autoapi_options:
    #   - members
    #   - inherited-members
    #   - show-inheritance
    #   - show-module-summary
    # autoapi_python_use_implicit_namespaces: True
    # autoapi_keep_files: True
    suppress_warnings:
      - "etoc.toctree"
      - "mystnb.unknown_mime_type"
    #nb_number_source_lines: True
    html_js_files: # to make plotly work
    - https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js
