name: Documentation

on:
  push:
    branches: main
  pull_request:
    types: [opened, reopened, synchronize]

permissions:
  contents: write

jobs:
  build:
    environment: github-actions
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: 3.11
          cache: pipenv

      - name: "Set-up virtual env"
        shell: bash
        run: |
          pip install pipenv
          pipenv sync --dev

      - name: Build docs
        shell: bash
        run: |
          source $(pipenv --venv)/bin/activate
          pip install -e . --no-deps
          pipenv run jb build doc
          touch doc/_build/html/.nojekyll
          mv doc/_build/html github-pages

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/master'
    permissions:
      pages: write
      id-token: write

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
